### ISSUE TITLE
用例报错

### ISSUE THREAD

**Issue by jackal186** [macaca-sample/sample-java#9]
![Uploading 2.jpg…]()

**Comment by jackal186** [comment]
2019-07-05 10:50:00 Response:Internal Server Error

com.alibaba.fastjson.JSONException: syntax error, pos 1, json : Internal Server Error

	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1361)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1268)
	at com.alibaba.fastjson.JSON.parse(JSON.java:137)
	at com.alibaba.fastjson.JSON.parse(JSON.java:128)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:201)
	at macaca.client.common.Utils.executeRequest(Utils.java:95)
	at macaca.client.common.Utils.deleteRequest(Utils.java:163)
	at macaca.client.common.Utils.request(Utils.java:174)
	at macaca.client.commands.Session.delSession(Session.java:50)
	at macaca.client.MacacaClient.quit(MacacaClient.java:1209)
	at macaca.client.DesktopSampleTest.tearDown(DesktopSampleTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by jackal186** [comment]
>> responseHandler.js:11:12 [master] pid:21276 Recieve HTTP Request from Client[2019-07-05 10:50:21]: method: DELETE url: /wd/hub/session/6ef8583d-7ad5-4f20-bf4c-fc7a4e27fa17, jsonBody: {}
>> responseHandler.js:56:12 [master] pid:21276 Send Error Respone to Client: TypeError: "file" argument must be a non-empty string
>> responseHandler.js:62:14 [master] pid:21276 TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:389:11)
    at exports.spawn (child_process.js:502:38)
    at Object.exports.execFile (child_process.js:218:15)
    at Object.exports.exec (child_process.js:148:18)
    at C:\Users\n00287216\AppData\Roaming\npm\node_modules\macaca-chrome\lib\helper.js:10:18
    at new Promise (<anonymous>)
    at Object._.exec (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\macaca-chrome\lib\helper.js:9:10)
    at Chrome.killChrome (C:\Users\XXXX\AppData\Roaming\npm\node_modules\macaca-chrome\lib\macaca-chrome.js:35:12)
    at Chrome.stopDevice (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\macaca-chrome\lib\macaca-chrome.js:54:54)
    at Object.delSession (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\controllers\session.js:89:18)

  TypeError: "file" argument must be a non-empty string
      at normalizeSpawnArguments (child_process.js:389:11)
      at exports.spawn (child_process.js:502:38)
      at Object.exports.execFile (child_process.js:218:15)
      at Object.exports.exec (child_process.js:148:18)
      at C:\Users\n00287216\AppData\Roaming\npm\node_modules\macaca-chrome\lib\helper.js:10:18
      at new Promise (<anonymous>)
      at Object._.exec (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\macaca-chrome\lib\helper.js:9:10)
      at Chrome.killChrome (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\macaca-chrome\lib\macaca-chrome.js:35:12)
      at Chrome.stopDevice (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\macaca-chrome\lib\macaca-chrome.js:54:54)
      at Object.delSession (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\controllers\session.js:89:18)

>> macaca-chromedriver.js:171:18 [master] pid:21276 chromedriver exit with code: null, signal: SIGTERM
